name: Packer

on:
  pull_request:
    branches:
      - master

jobs:
  echo-input:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          echo "Fetching packer"
          wget https://releases.hashicorp.com/packer/1.5.5/packer_1.5.5_linux_amd64.zip
          unzip packer_1.5.5_linux_amd64.zip
          chmod +x packer
          cd packer-test
          packer build -var-file=vars.json template.json
