name: Packer

on:
  pull_request:
    branches:
      - master

jobs:
  echo-input:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          script: |
                echo "Fetching packer"
               