name: Packer

on:
  push:
    paths-ignore:
      - README.md
      - vars.json
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          echo "Fetching packer"
          wget https://releases.hashicorp.com/packer/1.5.5/packer_1.5.5_linux_amd64.zip
          unzip packer_1.5.5_linux_amd64.zip
          chmod +x packer 
          curl -L https://github.com/aelsabbahy/goss/releases/latest/download/goss-linux-amd64 -o /usr/local/bin/goss
          chmod +rx /usr/local/bin/goss
          packer build -var-file=vars.json template.json
