name: Packer

on:
  pull_request:
    branches:
      - master

jobs:
  echo-input:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: packer-test
        run: |
          echo "Fetching packer"
          echo "Testing output"
               