name: PackerTest

on:
  pull_request:
    paths-ignore:
      - README.md
    branches:
      - master

jobs:
  test-and-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: |
          echo "Fetching packer"
          wget https://releases.hashicorp.com/packer/1.5.5/packer_1.5.5_linux_amd64.zip
          unzip packer_1.5.5_linux_amd64.zip
          chmod +x packer
          wget https://github.com/YaleUniversity/packer-provisioner-goss/releases/latest/download/packer-provisioner-goss-v3.0.2-linux-amd64.tar.gz
          tar -xvf packer-provisioner-goss-v3.0.2-linux-amd64.tar.gz
          chmod +x packer-provisioner-goss 
          packer validate -var-file=vars.json template.json
